// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWT0mpBlOCNQu-7lJZxOpWzlPKIt9KCY',
    appId: '1:542593105996:web:246a8169a8d290694434e9',
    messagingSenderId: '542593105996',
    projectId: 'barberbooking-a5feb',
    authDomain: 'barberbooking-a5feb.firebaseapp.com',
    storageBucket: 'barberbooking-a5feb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTlkiXURxCxspaVOZ2GOGTHSeDcfgb5g8',
    appId: '1:542593105996:android:12b3b8421ebc33b74434e9',
    messagingSenderId: '542593105996',
    projectId: 'barberbooking-a5feb',
    storageBucket: 'barberbooking-a5feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApo0wDcyx0GoW3lkhlgsCY4PSL7M2CHlc',
    appId: '1:542593105996:ios:02d646acf70ffd344434e9',
    messagingSenderId: '542593105996',
    projectId: 'barberbooking-a5feb',
    storageBucket: 'barberbooking-a5feb.appspot.com',
    iosClientId: '542593105996-o9qv3pct1ap68fkvqimbrfvjs0bj09ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApo0wDcyx0GoW3lkhlgsCY4PSL7M2CHlc',
    appId: '1:542593105996:ios:02d646acf70ffd344434e9',
    messagingSenderId: '542593105996',
    projectId: 'barberbooking-a5feb',
    storageBucket: 'barberbooking-a5feb.appspot.com',
    iosClientId: '542593105996-o9qv3pct1ap68fkvqimbrfvjs0bj09ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbershop',
  );
}
